/- Axiom audit: run with `lake env lean scripts/AxiomsReport.lean`.
   CI greps the output: structural theorems should introduce no axioms beyond
   the standard trio [propext, Classical.choice, Quot.sound], while
   `native_decide`-backed finite or rational audit endpoints may additionally
   use Lean.ofReduceBool and Lean.trustCompiler. -/
import Prop51

#print axioms Prop51.c_succ_succ
#print axioms Prop51.cList_getD_eq
#print axioms Prop51.unorm_corner_9_100
#print axioms Prop51.unorm_neg_9_60
#print axioms Prop51.bCoeff_neg_g_le_23
#print axioms Prop51.partitions_card_checks
#print axioms Prop51.coefficientNegativity_of_g_le_23
#print axioms Prop51.mem_partitions_iff
#print axioms Prop51.coefficientNegativity_of_g_le_23'
#print axioms Prop51.theta_expSeries
#print axioms Prop51.logDeriv_unique
#print axioms Prop51.Aseq_succ
#print axioms Prop51.Cseries_eq_expSeries_c
#print axioms Prop51.bridge_identity
#print axioms Prop51.bCoeff_eq_expCoeff
#print axioms Prop51.bSeries_official
#print axioms Prop51.c_pos
#print axioms Prop51.c_le_Aseq
#print axioms Prop51.expCoeff_mono
#print axioms Prop51.Cpow_mul_BSeriesQ
#print axioms Prop51.bCoeff_le_U
#print axioms Prop51.bCoeff_neg_of_unorm
#print axioms Prop51.coefficientNegativity_of_g_le_179

-- Layer B: dyadic interval arithmetic + interval certificate
#print axioms Prop51.shl_spec
#print axioms Prop51.DI.mem_mul
#print axioms Prop51.DI.mem_divNat
#print axioms Prop51.mem_cTab
#print axioms Prop51.mem_bTab
#print axioms Prop51.mem_qTab
#print axioms Prop51.checkPair_sound
#print axioms Prop51.checkRange_sound
#print axioms Prop51.checkRange_chunk1
#print axioms Prop51.unorm_neg_61_400
#print axioms Prop51.unorm_neg_9_400
#print axioms Prop51.coefficientNegativity_of_g_le_1199

-- Layer C groundwork: reciprocal binomials, d-normalization, compositions
#print axioms Prop51.sum_choose_recip_le
#print axioms Prop51.sum_choose_recip_inner_le
#print axioms Prop51.d_succ_succ
#print axioms Prop51.d_lb
#print axioms Prop51.d_ub
#print axioms Prop51.c_lb
#print axioms Prop51.c_ub
#print axioms Prop51.d_ratio_lb
#print axioms Prop51.Gcomp_le
#print axioms Prop51.sum_exp_le
#print axioms Prop51.one_add_inv_pow_le
#print axioms Prop51.factorial_lb
#print axioms Prop51.expCoeff_eq_sum_pow
#print axioms Prop51.abs_coeff_pow_le
#print axioms Prop51.abs_hpow_le
#print axioms Prop51.Eminus_split
#print axioms Prop51.Eminus_residual_le
#print axioms Prop51.DeltaRatTerm_two
#print axioms Prop51.DeltaRatTerm_succ
#print axioms Prop51.DeltaRatStepRatio_le_bound
#print axioms Prop51.DeltaRatTerm_succ_le
#print axioms Prop51.DeltaRatStepRatioBound_le_near
#print axioms Prop51.DeltaNearRatio_nonneg
#print axioms Prop51.DeltaNearRatio_lt_one_of_le_20
#print axioms Prop51.DeltaRatTerm_shifted_sum_le_geom
#print axioms Prop51.DeltaRatTerm_shifted_sum_le_inv_one_sub
#print axioms Prop51.DeltaRatTerm_Icc_sum_le_geom
#print axioms Prop51.DeltaRatTerm_Icc_sum_le_inv_one_sub
#print axioms Prop51.DeltaRatTerm_Icc_sum_le_near_geom
#print axioms Prop51.DeltaRatTerm_Icc_sum_le_near_inv_one_sub
#print axioms Prop51.DeltaRatTerm_Icc_sum_le_near_closed
#print axioms Prop51.DeltaRatNear_le_geomBound
#print axioms Prop51.DeltaRat_eq_near_add_far
#print axioms Prop51.DeltaRat_le_nearGeomBound_add_far
#print axioms Prop51.DeltaRatTerm_le_farTermBound
#print axioms Prop51.DeltaRatFar_le_termBound
#print axioms Prop51.DeltaRatFarTermBound_nonneg
#print axioms Prop51.DeltaRatFarTermBound_succ_le_half
#print axioms Prop51.DeltaRatFarTermBound_Icc_sum_le_two_first
#print axioms Prop51.DeltaRatFar_le_two_first
#print axioms Prop51.DeltaRatFarTermBound_le_inv_linear
#print axioms Prop51.DeltaRatFar_le_inv_start
#print axioms Prop51.DeltaRatFar_le_inv_m
#print axioms Prop51.DeltaNearGeomBound_le_final_range
#print axioms Prop51.DeltaRat_le_final_envelope
#print axioms Prop51.Eminus_normalized_residual_le_DeltaRat
#print axioms Prop51.Eminus_normalized_residual_le_final

-- Layer C sign-lock: completed `X`-side margin and its positive-saddle bridge
#print axioms Prop51.signLock_error_budget_zetaMax
#print axioms Prop51.signLockNearBase_lower
#print axioms Prop51.Xnorm_le_neg_final_margin_of_signLockNearBase
#print axioms Prop51.Xnorm_le_neg_final_margin
#print axioms Prop51.Xnorm_le_neg_signLockMargin
#print axioms Prop51.Unorm_neg_of_signLock_and_positiveEnvelopeBound

-- Layer C positive-saddle: current finite-window and large-tail audit interfaces
#print axioms Prop51.positiveSaddleEntropyShadowLargeExpProductPointwiseYRawUnitSoloCertificate_of_parts
#print axioms Prop51.PositiveSaddleEntropyShadowLargeExpProductPointwiseYRawUnitSoloCertificate.toSmallProductRawCertificate
#print axioms Prop51.PositiveSaddleEntropyShadowLargeExpProductPointwiseYRawUnitSoloCertificate.toTemperedProductRawCertificate
#print axioms Prop51.PositiveSaddleEntropyShadowLargeExpProductPointwiseYRawUnitSoloCertificate.toSoloYUnitCertificate
#print axioms Prop51.positiveLargeTailSoloYUnit_of_Y_bound
#print axioms Prop51.PositiveSaddleLargeTailSoloYBoundCertificate.toSoloYUnitCertificate
#print axioms Prop51.positiveSmallLargeProductRaw_of_BQ_bounds
#print axioms Prop51.positiveTemperedLargeProductRaw_of_BQ_bounds
#print axioms Prop51.PositiveSaddleLargeTailProductBoundsCertificate.toProductPointwiseYRawUnitSoloCertificate
#print axioms Prop51.PositiveSaddleLargeTailProductBoundsCertificate.toProductPointwiseYRawUnitSoloCertificate_of_soloYBound
#print axioms Prop51.positiveSmallExponentUpper_succ_le_of_small_branch
#print axioms Prop51.positiveSmallLargeExp_rawStepCleared_of_base_half
#print axioms Prop51.PositiveSaddleLargeTailCandidateSmallRawBaseHalfCertificate.toSmallRawStepCertificate
#print axioms Prop51.positiveSaddleLargeTailCandidateRawClearedStepCertificate_of_smallBaseHalf
#print axioms Prop51.positiveSaddleLargeTailCandidateAtomicCertificate_of_parts
#print axioms Prop51.PositiveSaddleEntropyShadowLargeExpCandidateSplitTemperedRawClearedUnitReserveBoundsCertificate.toCandidateAtomicCertificate
#print axioms Prop51.PositiveSaddleLargeTailCandidateAtomicCertificate.toRawClearedUnitReserveBoundsCertificate
#print axioms Prop51.PositiveSaddleLargeTailCandidateAtomicCertificate.toBoundsCertificate
#print axioms Prop51.positiveSaddleLargeTailPartsAuditCertificate_of_productBounds
#print axioms Prop51.positiveSaddleLargeTailPartsAuditCertificate_of_productAndSoloBounds
#print axioms Prop51.PositiveSaddleLargeTailBoundsPartsAuditCertificate.toLargeTailPartsAuditCertificate
#print axioms Prop51.PositiveSaddleLargeTailBoundsPartsAuditCertificate.toLargeTailAuditCertificate
#print axioms Prop51.PositiveSaddleLargeTailPartsAuditCertificate.toProductPointwiseYRawUnitSoloCertificate
#print axioms Prop51.PositiveSaddleLargeTailPartsAuditCertificate.toCandidateRawClearedUnitReserveBoundsCertificate
#print axioms Prop51.PositiveSaddleLargeTailPartsAuditCertificate.toCandidateBoundsCertificate
#print axioms Prop51.PositiveSaddleLargeTailPartsAuditCertificate.toLargeTailAuditCertificate
#print axioms Prop51.PositiveSaddleLargeTailAuditCertificate.toLargeTailPartsAuditCertificate
#print axioms Prop51.positiveSaddleLargeTailAtomicPartsAuditCertificate_of_productBounds
#print axioms Prop51.positiveSaddleLargeTailAtomicPartsAuditCertificate_of_productAndSoloBounds
#print axioms Prop51.PositiveSaddleLargeTailAtomicBoundsAuditCertificate.toAtomicPartsAuditCertificate
#print axioms Prop51.PositiveSaddleLargeTailAtomicBoundsAuditCertificate.toLargeTailPartsAuditCertificate
#print axioms Prop51.PositiveSaddleLargeTailAtomicBoundsAuditCertificate.toLargeTailAuditCertificate
#print axioms Prop51.PositiveSaddleLargeTailRawClearedUnitBoundsAuditCertificate.toBoundsPartsAuditCertificate
#print axioms Prop51.PositiveSaddleLargeTailRawClearedUnitBoundsAuditCertificate.toAtomicBoundsAuditCertificate
#print axioms Prop51.PositiveSaddleLargeTailRawClearedUnitBoundsAuditCertificate.toLargeTailAuditCertificate
#print axioms Prop51.PositiveSaddleLargeTailAtomicPartsAuditCertificate.toLargeTailAuditCertificate
#print axioms Prop51.PositiveSaddleLargeTailAuditCertificate.toLargeTailAtomicPartsAuditCertificate
#print axioms Prop51.coefficientNegativity_of_positiveSaddleFixedFiniteWindowCombinedProductNKChunkedTangentSoloNFixedEdgeKChunkedPartsAuditCertificate
#print axioms Prop51.coefficientNegativity_of_positiveSaddleFixedFiniteWindowCombinedProductNKChunkedTangentSoloNFixedEdgeKChunkedBoundsPartsAuditCertificate
#print axioms Prop51.coefficientNegativity_of_positiveSaddleFixedFiniteWindowCombinedProductNKChunkedTangentSoloNFixedEdgeKChunkedAtomicPartsAuditCertificate
#print axioms Prop51.coefficientNegativity_of_positiveSaddleFixedFiniteWindowCombinedProductNKChunkedTangentSoloNFixedEdgeKChunkedAtomicBoundsAuditCertificate
#print axioms Prop51.coefficientNegativity_of_positiveSaddleFixedFiniteWindowCombinedProductNKChunkedTangentSoloNFixedEdgeKChunkedRawClearedUnitBoundsAuditCertificate
