/- Compact public axiom audit for the theorem facade.

Run with:

  lake env lean scripts/PublicAxiomsReport.lean

The final theorem is expected to use the standard axioms plus
`Lean.ofReduceBool` and `Lean.trustCompiler`, coming from the finite
`native_decide` certificates.
-/
import Prop51
import Prop52.Theorem
import Prop52.Source
import Prop52.Assembly
import Prop52.Printed

#print axioms Prop51.Cseries_eq_expSeries_c
#print axioms Prop51.bSeries_official
#print axioms Prop51.bCoeff_le_U
#print axioms Prop51.coefficientNegativity
#print axioms Prop51.chenLarsonCoefficient_neg
#print axioms Prop51.chenLarsonCoefficient_ne_zero
#print axioms Prop51.bCoeff_neg_of_rectangle
#print axioms Prop52.correctedCoeff_eq_printedCoeff_add
#print axioms Prop52.correctedCoeffFast_eq
#print axioms Prop52.correctedCoeffMod_anchor
#print axioms Prop52.checkGeneratedModNat_9_prime1
#print axioms Prop52.checkGeneratedModNat_10_prime1
#print axioms Prop52.checkGeneratedModNat_11_prime1_chunks
#print axioms Prop52.checkGeneratedModNat_12_prime1_firstParts
#print axioms Prop52.checkGeneratedModNat_13_prime1_firstParts
#print axioms Prop52.finitePrime1_expListModNat_cast
#print axioms Prop52.finitePrime1_hCoeffModNat_cast
#print axioms Prop52.finitePrime1_kCoeffModNat_cast
#print axioms Prop52.finitePrime1_correctedCoeffModNat_cast
#print axioms Prop52.finitePrime1_correctedCoeffMod_ne_of_checkGeneratedChunks
#print axioms Prop52.finitePrime1_correctedCoeffMod_ne_of_checkGeneratedFirstParts
#print axioms Prop52.finitePrime1_correctedCoeffMod_ne_9_generated
#print axioms Prop52.finitePrime1_correctedCoeffMod_ne_10_generated
#print axioms Prop52.finitePrime1_correctedCoeffMod_ne_11_generated
#print axioms Prop52.finitePrime1_correctedCoeffMod_ne_12_generated
#print axioms Prop52.finitePrime1_correctedCoeffMod_ne_13_generated
#print axioms Prop52.finitePrime1_correctedCoeffMod_ne_9_13_generated
#print axioms Prop52.RatGood_iff_not_dvd
#print axioms Prop52.RatGood_mul
#print axioms Prop52.RatGood_add
#print axioms Prop52.RatGood_sub
#print axioms Prop52.RatGood_list_sum
#print axioms Prop52.RatGood_list_sum_of_sublist
#print axioms Prop52.RatGood_list_sum_of_suffix
#print axioms Prop52.RatGood_getD
#print axioms Prop52.ratCast_mul_of_good
#print axioms Prop52.ratCast_add_of_good
#print axioms Prop52.ratCast_sub_of_good
#print axioms Prop52.ratCast_mul_of_RatGood
#print axioms Prop52.ratCast_add_of_RatGood
#print axioms Prop52.ratCast_sub_of_RatGood
#print axioms Prop52.ratCast_list_sum_of_suffix_good
#print axioms Prop52.finitePrime1_RatGood_expList_of_good
#print axioms Prop52.finitePrime1_ratCast_expList_of_RatGood
#print axioms Prop52.finitePrime1_RatGood_expCoeff_of_good
#print axioms Prop52.finitePrime1_ratCast_expCoeff_of_RatGood
#print axioms Prop52.finitePrime1_ratCast_sPower_of_good
#print axioms Prop52.finitePrime1_ratCast_sPower_of_suffix_good
#print axioms Prop52.finitePrime1_RatGood_sPower_of_suffix_good
#print axioms Prop52.finitePrime1_sPower_suffix_good_auto
#print axioms Prop52.finitePrime1_RatGood_sPower_auto
#print axioms Prop52.finitePrime1_ratCast_sPower_auto
#print axioms Prop52.finitePrime1_ratCast_markedWeight_of_good
#print axioms Prop52.finitePrime1_ratCast_markedWeight_of_suffix_good
#print axioms Prop52.finitePrime1_RatGood_markedWeight_of_suffix_good
#print axioms Prop52.finitePrime1_markedWeight_suffix_good_auto
#print axioms Prop52.finitePrime1_RatGood_markedWeight_auto
#print axioms Prop52.finitePrime1_ratCast_markedWeight_auto
#print axioms Prop52.finitePrime1_ratCast_hCoeff_of_good
#print axioms Prop52.finitePrime1_RatGood_hCoeff_of_suffix_good
#print axioms Prop52.finitePrime1_ratCast_hCoeff_of_suffix_good
#print axioms Prop52.finitePrime1_RatGood_hCoeff_auto
#print axioms Prop52.finitePrime1_ratCast_hCoeff_auto
#print axioms Prop52.finitePrime1_ratCast_expCoeff_of_good
#print axioms Prop52.finitePrime1_ratCast_fCoeff_of_good
#print axioms Prop52.finitePrime1_RatGood_fCoeff_auto
#print axioms Prop52.finitePrime1_ratCast_fCoeff_auto
#print axioms Prop52.finitePrime1_ratCast_kCoeff_of_suffix_good
#print axioms Prop52.finitePrime1_RatGood_kCoeff_of_suffix_good
#print axioms Prop52.finitePrime1_ratCast_kCoeff_of_suffix_RatGood
#print axioms Prop52.finitePrime1_RatGood_kCoeff_auto
#print axioms Prop52.finitePrime1_ratCast_kCoeff_auto
#print axioms Prop52.finitePrime1_ratCast_correctedCoeffFast_of_good
#print axioms Prop52.finitePrime1_ratCast_correctedCoeffFast_of_suffix_good
#print axioms Prop52.finitePrime1_correctedCoeffFast_conv_suffix_good_auto
#print axioms Prop52.finitePrime1_ratCast_correctedCoeffFast_auto
#print axioms Prop52.correctedCoeff_neg_large_of_printed
#print axioms Prop52.correctedCoeff_nonvanishing_of_finite_and_printed
#print axioms Prop52.correctedCoeff_ne_2_8
#print axioms Prop52.correctedCoeff_ne_9_13_generated
#print axioms Prop52.correctedCoeff_ne_9_13
#print axioms Prop52.correctedCoeff_ne_2_13
#print axioms Prop52.correctedCoeff_finite_nonvanishing
#print axioms Prop52.printedCoeffNegativityLarge_of_mid_tail
#print axioms Prop52.printedCoeffNegativityTail_of_normalizedLowerBound
#print axioms Prop52.printedCoeffNegativityLarge_of_mid_normalizedTail
#print axioms Prop52.coeff_printedFullFSeries
#print axioms Prop52.coeff_printedFullFSeries_mul_KSeries
#print axioms Prop52.coeff_printedFullSeries_eq_printedCoeff
#print axioms Prop52.coeff_printedTailHighESeries_eq_zero_of_le_p
#print axioms Prop52.coeff_printedTailHighESeries_eq_neg_hCoeff_of_gt_p_le_a
#print axioms Prop52.coeff_printedTailHighESeries_piecewise
#print axioms Prop52.coeff_printedTailHighKSeries_eq_zero_of_le_p
#print axioms Prop52.printedFullFSeries_eq_low_mul_high
#print axioms Prop52.printedFullKSeries_eq_low_add_high
#print axioms Prop52.coeff_printedTail_series_split_eq_printedCoeff
#print axioms Prop52.coeff_printedTailHighESeries_mul_W_eq_piecewiseSum
#print axioms Prop52.coeff_printedTailHighESeries_mul_highKSeries_eq_piecewise
#print axioms Prop52.coeff_printedTailE_mul_highE_mul_highK_eq_piecewiseSum
#print axioms Prop52.coeff_printedTailHighESeries_mul_W_eq_omega_sub_HRaw
#print axioms Prop52.coeff_printedTailE_mul_highE_mul_highK_eq_KRaw
#print axioms Prop52.printedCoeff_eq_tail_raw_split
#print axioms Prop52.printedTailExactSplit_closed
#print axioms Prop52.printedTailNormalizedLowerBound_of_split_errorBounds
#print axioms Prop52.printedCoeffNegativityTail_of_split_errorBounds
#print axioms Prop52.printedTailNormalizedLowerBound_of_errorBounds
#print axioms Prop52.printedCoeffNegativityTail_of_errorBounds
#print axioms Prop52.coeff_printedTailESeries
#print axioms Prop52.coeff_printedTailESeries_mul_lowJSeries
#print axioms Prop52.coeff_printedTailWSeries
#print axioms Prop52.hCoeff_nonneg_of_partition
#print axioms Prop52.hCoeff_le_twoM_c_of_partition
#print axioms Prop52.hCoeff_le_M_two_sub_twopow_c_of_partition
#print axioms Prop52.markedWeight_nonneg_of_coeffs
#print axioms Prop52.markedWeight_le_M_div_two_pow_of_partition
#print axioms Prop52.kCoeff_nonneg
#print axioms Prop52.kCoeff_le_partition_marked_bound
#print axioms Prop52.kCoeff_le_two_hCoeff_of_partition
#print axioms Prop52.printedLargeMargin_pos
#print axioms Prop52.printedLargeMargin_pos_150
#print axioms Prop52.gammaExponentBound_lt
#print axioms Prop52.factorialGas_prefix_base4
#print axioms Prop52.factorialGas_prefix_base4_weighted
#print axioms Prop52.factorialGas_prefix_base2
#print axioms Prop52.factorialGas_prefix_base2_weighted
#print axioms Prop52.factorialGas_prefix_tail_base4
#print axioms Prop52.factorialGas_prefix_tail_base4_weighted
#print axioms Prop52.factorialGas_prefix_tail_base2
#print axioms Prop52.factorialGas_prefix_tail_base2_weighted
#print axioms Prop52.truncationResidue_150
#print axioms Prop52.truncationResidue_151
#print axioms Prop52.truncationResidue_152
#print axioms Prop52.truncationResidue_153
#print axioms Prop52.truncationResidue_154
#print axioms Prop52.truncationResidue_155
#print axioms Prop52.truncationResidue_156
#print axioms Prop52.truncationResidue_157
#print axioms Prop52.truncationResidueScaled_step8
#print axioms Prop52.truncationResidue_bound
#print axioms Prop52.printedTailMainLowerBound_of_gammaIntegralLowerBound
#print axioms Prop52.printedTailX0Bound1_lt
#print axioms Prop52.printedTailX0Bound2_lt
#print axioms Prop52.printedTailX0Bound3_lt
#print axioms Prop52.printedTailX0Bound4_lt
#print axioms Prop52.printedTailX2Bound1_lt
#print axioms Prop52.printedTailX2Bound2_lt
#print axioms Prop52.printedTailX2Bound3_lt
#print axioms Prop52.printedTailX2Bound4_lt
#print axioms Prop52.printedTailAbsoluteMoment0_budget
#print axioms Prop52.printedTailAbsoluteMoment1_budget
#print axioms Prop52.printedTailMajorantMomentBounds_of_wPointMomentBounds
#print axioms Prop52.printedTailOmegaCoeffMajorant_of_wPointBoundX2
#print axioms Prop52.printedTailWPointMomentBounds_closed
#print axioms Prop52.printedTailWPointBoundX2_closed
#print axioms Prop52.printedTailOmegaExpBudget_bound
#print axioms Prop52.printedTailOmegaErrorBound_of_coeffMajorant
#print axioms Prop52.x0Endpoint1_lt
#print axioms Prop52.x0Endpoint2_lt
#print axioms Prop52.x0Endpoint3_lt
#print axioms Prop52.x0Endpoint4_lt
#print axioms Prop52.x2Endpoint1_lt
#print axioms Prop52.x2Endpoint2_lt
#print axioms Prop52.x2Endpoint3_lt
#print axioms Prop52.x2Endpoint4_lt
#print axioms Prop52.correctedCoeff_nonvanishing_of_printed
#print axioms Prop52.correctedCoeff_nonvanishing_of_printed_mid_tail
#print axioms Prop52.correctedCoeff_nonvanishing_of_printed_mid_normalizedTail
#print axioms Prop52.correctedCoeff_nonvanishing_of_printed_mid_split_errorBounds
#print axioms Prop52.correctedCoeff_nonvanishing_of_printed_mid_errorBounds
#print axioms Prop52.correctedCoeff_nonvanishing_of_printed_mid_moments_errorBounds
#print axioms Prop52.correctedCoeff_nonvanishing_of_printed_mid_moments_eMoment_errorBounds
#print axioms Prop52.correctedCoeff_nonvanishing_of_printed_mid_majorantMoments_errorBounds
#print axioms Prop52.correctedCoeff_nonvanishing_of_printed_mid_majorantMoments_omegaCoeff
#print axioms Prop52.correctedCoeff_nonvanishing_of_printed_mid_majorantMoments_wPointX2
#print axioms Prop52.correctedCoeff_nonvanishing_of_printed_mid_wPointMoments_wPointX2
#print axioms Prop52.correctedCoeff_nonvanishing_of_printed_mid_gammaIntegral_wPointMoments_wPointX2
#print axioms Prop52.correctedCoeff_nonvanishing_of_printed_mid_gammaIntegral_wPointX2
#print axioms Prop52.correctedCoeff_nonvanishing_of_printed_mid_gammaIntegral

-- Marked Proposition 5.2 theorems retained behind the source facade:
#print axioms Prop52.correctedCoeff_nonvanishing
#print axioms Prop52.correctedCoeff_neg

-- Source bridge and source-shaped public Proposition 5.2 theorems:
#print axioms Prop52.sourceCorrectedCoeff_eq
#print axioms Prop52.sourceCorrectedCoeff_nonvanishing
#print axioms Prop52.sourceCorrectedCoeff_neg
#print axioms Prop52.chenLarsonProp52Coefficient_nonvanishing
#print axioms Prop52.chenLarsonProp52Coefficient_neg
